---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr4k-volsync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: radarr4k-volsync
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/radarr4k'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .AWS_ACCESS_KEY_ID }}'
        AWS_SECRET_ACCESS_KEY: '{{ .AWS_SECRET_ACCESS_KEY }}'
  dataFrom:
    - extract:
        key: volsync-restic-template
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr4k-config-v1
  labels:
    app.kubernetes.io/name: radarr4k
    app.kubernetes.io/instance: radarr4k
    app.kubernetes.io/part-of: radarr4k
spec:
  accessModes: ["ReadWriteOnce"]
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: radarr4k-bootstrap
  resources:
    requests:
      storage: 5Gi # must match the ReplicationDestination `.spec.capacity` below
  storageClassName: ceph-block
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: radarr4k-bootstrap
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
spec:
  trigger:
    manual: restore-once
  restic:
    repository: radarr4k-volsync
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 8Gi
    storageClassName: ceph-block
    accessModes: ["ReadWriteOnce"]
    capacity: 5Gi # must match the PersistentVolumeClaim `.resources.requests.storage` size above
    moverSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: radarr4k
spec:
  sourcePVC: radarr4k-config-v1
  trigger:
    schedule: "0 7 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: radarr4k-volsync
    volumeSnapshotClassName: csi-ceph-blockpool
    cacheCapacity: 8Gi
    cacheStorageClassName: openebs-hostpath
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: ceph-block
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
    retain:
      daily: 30
      within: 3d
